Первое выполененное задание
Lyashka/FrontLoops-tasks pull request #1
Opened 2019-06-04 12:42 UTC by Lyashka

2019-06-05 15:31 UTC, VitalyKrenel commented on index.html
> +      <img src="img/device.svg" alt="mobile" width="65" height="65">
Размеры изображения лучше не указывать через атрибуты - для представления используют именно CSS, чтобы не нужно было гадать, почему данная картинка такого размера.
Если определять визуальную составляющую только через стили, то всегда достаточно взглянуть на класс и понять.

2019-06-06 20:37 UTC, VitalyKrenel commented on index.html
>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
Объясни, что значит данный meta тег?

2019-06-06 21:22 UTC, VitalyKrenel requested changes

2019-06-06 21:22 UTC, VitalyKrenel commented on index.html
> +      <img src="img/laptop.svg" alt="desktop" width="65" height="65">
См. комментарий выше.

2019-06-06 21:22 UTC, VitalyKrenel commented on index.html
> +      <h1>Mobile</h1>
На странице должен присутствовать только один тег h1. Обычно там содержится название страницы или наиболее важная информация страницы.

О заголовках рекомендую HTML шорты: https://www.youtube.com/watch?v=atXxkKjPbN8

В случае с данным заданием, можешь представить, что у тебя уже где-то есть h1 и использовать менее важные заголовки.

2019-06-06 21:22 UTC, VitalyKrenel commented on index.html
> +      <img src="img/monitor.svg" alt="TV" width="65" height="65">
Alt атрибут должен кратко описывать содержимое картинки. Например, можно написать "Vector picture of the TV". В картинках со смыслом поступай именно так.

Однако в данном случае, это изображение не несущее никакой смысловой нагрузки или, иначе, презентационное. В подобных случаях работает особое правило: необходимо добавить пустой `alt` и специальный атрибут `aria-role` со значением `presentation`:
```
<img src="..." alt="" aria-role="presentation" />
```

2019-06-06 21:22 UTC, VitalyKrenel commented on index.html
> +    <div class="mobile block">
Для такого "компонента" вполне можно использовать `article` элемент. Он отлично подходит для самодостаточных компонентов, которые можно свободно переносить / переиспользовать между разными страницами.

2019-06-06 21:22 UTC, VitalyKrenel commented on styles.css
> +  font-family: "Roboto", sans-serif;
Кавычки необязательно использовать. Когда-то рекомендовалось (но не требовалось!), сейчас уже не актуально.

2019-06-06 21:22 UTC, VitalyKrenel commented on styles.css
> +  border: 1px solid #ffffff;
Зачем нужен border?

2019-06-06 21:22 UTC, VitalyKrenel commented on styles.css
> +  border: 1px solid #ffffff;
Зачем нужен border?

2019-06-06 21:22 UTC, VitalyKrenel commented on styles.css
> +  min-width: 250px;
Почему min-width / min-height вместо обычных width / height?

2019-06-06 21:22 UTC, VitalyKrenel commented on styles.css
> +}
Общая проблема для всего файла: ты полагаешься на отступы, которые имеются у элементов по умолчанию, в частности у элементов `p` и `h` - так лучше не делать, поскольку они могут быть сброшены кем-нибудь до нулей, например так:
```
* {
  margin: 0;
  padding: 0;
}
```
Пусть твой компонент лучше сам явно описывает свою геометрию и позиционирование. Тогда ничто снаружи ненамеренно не вмешается и компонент можно будет переносить в любой проект, в котором могут быть какие- то другие базовые стили для `p` и `h`.

2019-06-06 21:22 UTC, VitalyKrenel commented on styles.css
> +.main div:hover {
Сверху ты использовала класс для стилизации, а здесь уже тег - Почему не `.main .block:hover`?

2019-06-07 16:03 UTC, Lyashka commented on index.html
>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
Он задаёт кодировку документа, один из обязательных meta тегов, чтобы не было "абракадабры" на странице.

2019-06-07 16:05 UTC, Lyashka commented on index.html
> +      <h1>Mobile</h1>
Постоянно я забываю про h1, ты мне уже говорил мне про этот косяк как-то, будем исправляться.

2019-06-07 16:10 UTC, Lyashka commented on index.html
> +    <div class="mobile block">
Про теги article, section, div - до сих пор не понимаю как именно выбрать где и какой лучше использовать.

2019-06-07 16:12 UTC, Lyashka commented on styles.css
> +  border: 1px solid #ffffff;
Мне так в начале легче было разграничить область, которая потом через hover "проявлялась", не убрала потом, косяк.

2019-06-07 16:13 UTC, Lyashka commented on styles.css
> +  min-width: 250px;
Пыталась сделать универсальные контейнеры, как учили в академии, где в независимости от объёма информации, всегда всё красивым остаётся.

2019-06-07 16:16 UTC, Lyashka commented on styles.css
> +.main div:hover {
Даже не знаю как ответить на это, просто.

2019-06-08 16:04 UTC, Lyashka commented on styles.css
> +}
Получается нужно обнулять все базовые отступы элементов, типа `p` и `h`, а затем уже позиционировать все компоненты страницы?

2019-06-09 10:21 UTC, VitalyKrenel commented on index.html
>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
Комментарий обычно относится к строке, под которой он находится 😄 
Я про
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

2019-06-09 11:28 UTC, VitalyKrenel requested changes

2019-06-09 11:28 UTC, VitalyKrenel commented on index.html
> +    <div class="mobile block">
Поискал статьи, которые помогли бы понять между ними разницу - одна из наиболее доступных ["Секции для контента в HTML5 — div или section или article?"](http://front-end.su/2015/11/01/div-or-section-or-article/)

Мой короткий список правил:
- `<section>` представляет __отдельную, но не независимую__, часть целой страницы, используй для группировки части разметки, которая связана общим смыслом.
- `<article>` представляет __отдельный и независимый контент__, то есть такой, который можно спокойно переносить между страницы сайта и он не потеряет смысл. Используй для группировки связанной между собой разметки, которая не привязана к странице и не является её неотъемлемой частью.
- `<div>` используй для всего остального, включая стилизацию визуально связанных элементов, но не связанных никак смыслом. По сути div - это разного рода обертки (wrappers) и контейнеры для остальных элементов, когда нужна стилизация, но не нужна (или не важна) семантика.

Пример section:
- Результаты выдачи поиска по запросу можно сгруппировать в section, поскольку отдельно от страницы они не имеют смысла (как разобраться к что это за разрозненные куски 

Пример article:
- Виджет социальной сети на странице. Он как на другой странице, так и вообще без страницы представляет список постов из социальной сети. Ни в нём, ни на странице ничего не изменится с точки зрения пользователя, если его убрать.

Пример div:
- Дизайнеру понадобилось, чтобы 3 рядом стоящих параграфа были 
отделены от остального контента б**о**льшими отступами 🤷‍♂ 
Все параграфы связанны на данной странице, поэтому эти 3 отдельные никак не отличаются от остальных, поэтому чисто в целях стилизации имеет смысл использовать просто div и не переживать.

2019-06-09 11:28 UTC, VitalyKrenel commented on index.html
> +      <h1>Mobile</h1>
👍

2019-06-09 11:28 UTC, VitalyKrenel commented on styles.css
> +  min-width: 250px;
Отличный подход: помнить про разное количество контента 👍 

Особенно важно учитывать в двух категориях элементов:
- В тех, для которых контент генерируется автоматически (т.е. приходит с бекенда или добавляется самим пользователем)
- В универсальных компонентах, которые могут переиспользоваться в разных местах и для разного контента (хоть и заранее определенного).

2019-06-09 11:28 UTC, VitalyKrenel commented on styles.css
> +}
Ответил в чате

2019-06-09 11:42 UTC, VitalyKrenel commented on styles.css
> +}
Обычно в ручную переопределяют отступы, обнуляя их и добавляя какие требуется. Например
```css
margin: 16px 0:
```

Теперь отступы пот вертикали всегда стабильно 16px, а по горизонтали их не будет ни в каком браузере.

А касательно * { ... } - данный метод называется reset, когда все стили обнуляются до единых начальных значений, чтобы полностью исключить вероятность, что ты будешь полагаться на какие-то дефолтные значения. 
Только полноценный reset.css выглядит так: https://gist.github.com/DavidWells/18e73022e723037a50d6

Решение с единым селектор - совсем простое, просто чтобы самый популярный кейс с дефолтными margin'ами и padding'ами закрыть.

2019-06-09 15:03 UTC, Lyashka commented on index.html
>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
Этот `meta` уже был, я решила его оставить, насколько я поняла, он даёт общую информацию о странице.

2019-06-17 06:47 UTC, VitalyKrenel approved these changes

2019-06-17 06:47 UTC, VitalyKrenel commented on index.html
>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
@Lyashka Пробегись по странице на mdn, покрывающий данный мета тег: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

2019-07-05 08:40 UTC, merged