Второе выполненное задание FrontLoops
Lyashka/FrontLoops-tasks pull request #3
Opened 2019-07-05 09:08 UTC by Lyashka

Второе выполненное задание

2019-07-08 19:28 UTC, VitalyKrenel requested changes

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/index.html
> +        <h5>Visa</h5>
Почему ты используешь здесь h5, если на странице не присутствуют остальные заголовки более высокого уровня h1-h4 теги? 

Если тебе необходимо стилизовать надписи, сделав их определенного размера, то используй для этого CSS - не нужно полагаться на базовое представление заголовков.

HTML отвечает за данные, CSS - за представление. Не стоит менять их обязанности местами.

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/index.html
> +        <h5>Visa</h5>
В данном случае я рекомендую вообще не использовать теги заголовков, поскольку никакой смысловой секции здесь нет (outline). 
Достаточно использовать стандартный тег для текста `p` с классом, придающим ему нужный вид.

Лучше всегда, где не требуется определить смысловую вложенность контента, использовать `p`.

P.S. под "смысловой вложенностью" я подразумеваю отношение между частями контента, когда одна часть является составляющей другой части. Как например, когда ты пишешь h1 на странице, а после где-то пишешь один или несколько h2 - h2 являются частью основного контента, который расположен после h1.

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/index.html
> +    <div class="button">
Почему div, а не button, если это кнопка?

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/index.html
> +      <a href="#">Next step</a>
Допустим при клике по кнопке "Next step" происходит переход на другую страницу. Однако у тебя происходит данный переход только при клике по тексту, а не по всей кнопке. Почему?

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/index.html
> +      <h3>Payment method</h3>
См. комментарий ниже

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/styles.css
> +  vertical-align: middle;
Зачем нужен vertical-align?

2019-07-08 19:28 UTC, VitalyKrenel commented on task-2/styles.css
> +div.first {
Почему `div.first`, а не просто `.first`?

2019-07-18 06:06 UTC, Lyashka commented on task-2/index.html
> +        <h5>Visa</h5>
Поняла, исправлю.

2019-07-18 06:13 UTC, Lyashka commented on task-2/index.html
> +    <div class="button">
Из-за достаточного промежутка времени, я уже не помню точную причину, почему именно div сделала, но что-то связанное со стилями CSS было.

2019-07-18 06:14 UTC, Lyashka commented on task-2/index.html
> +      <a href="#">Next step</a>
Надо обернуть в ссылку весь div, а не только текст.

2019-07-18 06:19 UTC, Lyashka commented on task-2/styles.css
> +  vertical-align: middle;
Изначально у меня не было жёстко заданы ширина и высота, и я выравнивала вертикально их, не удалила.

2019-07-18 06:31 UTC, Lyashka commented on task-2/styles.css
> +div.first {
Если написать просто `.first`, то мы не добьёмся нужного результата (первый кружок "активный").

2019-07-18 08:54 UTC, VitalyKrenel commented on task-2/index.html
> +    <div class="button">
Попробуй сделать с помощью button. Не получится - обсудим

2019-07-18 08:57 UTC, VitalyKrenel commented on task-2/styles.css
> +div.first {
Не понял что значит "не добьемся нужного результата"? Попробуй сделать так, чтобы без повышения специфичности стили применялись.
Если описывать стили не осторожно, то легко можно увязнуть в войне специфичностей. Нужно стараться не использовать больший вес там, где без него возможно обойтись.

2019-07-19 05:30 UTC, Lyashka commented on task-2/styles.css
> +div.first {
"не добьемся нужного результата" - наш первый кружок не изменит цвет на более тёмный

2019-07-20 11:54 UTC, VitalyKrenel commented on task-2/index.html
> +    <a href="#" class="button">
Согласно спецификации, вкладывать интерактивные элементы вроде button, в ссылку нельзя (такой HTML будет невалидным). 

Я на самом деле добавлял комментарий, чтобы ты обратила внимание на такую деталь: это многошаговая форма, которая работала бы за счет изменения состояния при клике на кнопку и страница на которой пользователь находился, не изменялась бы, только сама форма.
Поэтому тут нет необходимости в ссылке в целом. Достаточно использовать button.

2019-07-20 11:54 UTC, VitalyKrenel commented on task-2/styles.css
> +  vertical-align: middle;
vertical-align не удалила снова 😄

2019-07-20 11:54 UTC, VitalyKrenel commented on task-2/styles.css
> +.first:first-child {
Всё равно не понимаю, зачем ты что-то добавляешь к классу 🤔 

Ты же определяешь первый элемент уже по самому классу (он у тебя специально добавлен только к первому элементу).
```html
 <div class="circle">
  <div class="first"></div>
  <div></div>
  <div></div>
</div>
```

Если требуется first-child из детей элемента .circle, то можно было бы написать
`.circle > *:first-child`, но это излишне, лучше заводить под это отдельный класс, как у тебя (`.first`).

2019-07-20 12:13 UTC, Lyashka commented on task-2/styles.css
> +.first:first-child {
Я до этого писала, что если написать `.first {}` просто, то не будут применяться к нему стили (кружок не будет активным, тёмным)

2019-07-20 12:14 UTC, Lyashka commented on task-2/index.html
> +    <a href="#" class="button">
И опять я очень важную вещь забыла, спецификацию :/

2019-07-20 12:20 UTC, VitalyKrenel commented on task-2/index.html
> +    <a href="#" class="button">
Всё в порядке, это тонкости, которые по мере использования HTML и CSS изучаешь

2019-07-20 12:22 UTC, VitalyKrenel commented
Проверка todo листа:
- [ ] Удалить vertical-align

2019-07-20 13:14 UTC, VitalyKrenel approved these changes

2019-07-20 13:20 UTC, merged