Третье выполненное задание FrontLoops
Lyashka/FrontLoops-tasks pull request #4
Opened 2019-07-05 09:09 UTC by Lyashka

Третье выполненное задание

2019-07-10 06:09 UTC, VitalyKrenel commented
Не забывай про правило написания коммитов. 
Принятое у нас с тобой соглашение: отглагольное существительное + суть изменений, например

```
Добавление кнопки для отправки данных формы контактов
Улучшение семантики элемента выбора платежной системы
```

Хорошие сообщения коммитов - это инвестиция в своё собственное будущее и будущее любого проекта. Если ты вернешься к работе после большого перерыва, то история с хорошими сообщениями будет помогать понимать причины принятия определенных решений в коде, если ты вдруг встретишь странный или неожиданный кусок. 

А для проекта это ценно, потому что если кто-то возьмётся после тебя развивать проект, то хорошая история ему обеспечит более простой старт - для прояснения непонятного кода вполне достаточно будет написать git blame и посмотреть, что, зачем и почему автор там делал.

![image](https://user-images.githubusercontent.com/17354709/60944724-4bdbeb80-a2f2-11e9-8970-bf934de0c2a7.png)

2019-07-10 07:32 UTC, VitalyKrenel requested changes

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/index.html
> +        <h3>SimpleWheels</h3>
См. комментарий ко второму заданию: https://github.com/Lyashka/FrontLoops-tasks/pull/3#discussion_r301258764

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/styles.css
> +  font: 16px Roboto;
При использовании кастомных шрифтов рекомендуют указывать семью шрифтов и fallback шрифт, которые могут быть использованы, если кастомный не будет загружен (проблемы с сетью, etc.). 

В данном случае это может быть например такой подход
```css
font: 16px Roboto, Helvetica, Arial, sans-serif;
```
Где Arial и Helvetica - это fallback шрифты для macOS и Windows соответственно, которые применятся, если невозможно будет загрузить Robot. Ключевое слово `sans-serif` - это семья шрифтов, к которой относятся все три шрифта. 

Семью всегда стоит указывать, чтобы, если никакой шрифт достать не удастся, браузер мог подбрать, что-то подходящее из доступного у пользователя в системе. Это лучше, чем не показывать контент совсем.

Ситуация кажется достаточно надуманной, но пользователей у твоего продукта может быть огромное количество и, как следствие, множество разных устройств. Не хорошо, если кто-нибудь споткнется об проблему, которую можно в самом начале еще решить.

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/styles.css
> +  font: 16px Roboto;
Про font-family можно почитать еще на mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/styles.css
> +  height: 395px;
Почему решила использовать жестко заданные значения? Как будет выглядеть карточка, если будет много покупок?

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/styles.css
> +  transition-duration: 0.5s;
Почему transition-duration в псевдо-классе `:hover`, а transition-property в `.account img`?

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/styles.css
> +  height: 395px;
![image](https://user-images.githubusercontent.com/17354709/60946458-f6eea400-a2f6-11e9-862e-b3554f6f707d.png)

2019-07-10 07:32 UTC, VitalyKrenel commented on task-3/styles.css
> +  height: 395px;
В реальной работе, если серьезно подходить к проблеме, то должен быть дизайн для сценария, когда много товаров в корзине, не простое вмещение в карточку всех товаров сразу.

Например, специальная кнопка-надпись "Еще 12 товаров", которая по клику показывает большой вариант карточки с приобретенными товарами.

В работе дизайнер мог это не предусмотреть и поэтому в большинстве случае тебе стоит подойти к нему (или продакт менеджеру, если такой имеется) и объяснить проблему, сказать как ты можешь решить проблему переполнения контентом сейчас и попросить реализовать отдельный дизайн для этого сценария, если он посчитает это целесообразным.

2019-07-10 08:11 UTC, VitalyKrenel commented
Кстати, у меня не отцентрована карточка на странице:

![image](https://user-images.githubusercontent.com/17354709/60952137-5eaaec00-a303-11e9-8060-c4cda22100af.png)

2019-07-10 08:14 UTC, VitalyKrenel commented on task-3/styles.css
> +  text-transform: uppercase;
Отличное решение для изменения внешнего вида текста использовать CSS 👍
Если потребуется поменять из uppercase во внешний или переопределить дизайн для total в другом месте, это будет крайне легко сделать.

2019-07-18 05:59 UTC, Lyashka commented on task-3/index.html
> +        <h3>SimpleWheels</h3>
Будет исправлено.

2019-07-18 06:00 UTC, Lyashka commented on task-3/styles.css
> +  font: 16px Roboto;
Были эти советы про шрифты в теории, помню... Исправлю.

2019-07-18 06:02 UTC, Lyashka commented on task-3/styles.css
> +  height: 395px;
Универсальная/адаптивная вёрстка это, конечно, мощно и сложно, мне переделать?

2019-07-18 06:03 UTC, Lyashka commented on task-3/styles.css
> +  transition-duration: 0.5s;
Пользовалась в проекте трансформациями впервые, смотрела на пример в интернете.

2019-07-18 09:00 UTC, VitalyKrenel commented on task-3/styles.css
> +  height: 395px;
В данном случае достаточно предусмотреть то, что записей может быть много. Сделай так, чтобы этот блок вмещал весь контент в себя, независимо от того, сколько покупок.

2019-07-18 09:04 UTC, VitalyKrenel commented on task-3/styles.css
> +  transition-duration: 0.5s;
Transition - в русском языке обычно называют "переходами", поскольку есть transform, который как раз про трансофрмации.

Используя transition-* свойства, все данные необходимо помещать в селектор с начальным состоянием (у тебя это `.account img {}`).

```css
.account img {
  transition-property: box-shadow;
  transition-duration: 0.5s;
}
```

А в селекторе, который является каким-либо следующим состоянием, просто описывать сами измененные стили.

2019-07-23 12:11 UTC, VitalyKrenel approved these changes

2019-07-23 12:14 UTC, merged