Третье выполненное задание FrontLoops
Lyashka/FrontLoops-tasks pull request #5
Opened 2019-07-23 09:44 UTC by Lyashka

2019-07-28 09:28 UTC, VitalyKrenel requested changes

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/index.html
> +    <div class="circle"></div>
Немного по семантике именования:
Подбирай названия для классов, компонентов и т.д. так, чтобы название отражало, что это, а не как оно выглядит. Например, этот кружок лучше было бы назвать `user presence`или как-то схоже, чтобы отразить, что этот элемент отвечает за статус пользователя (онлайн или оффлайн).

Во-первых, с такими классами легче работать, потому что ты понимаешь за что он отвечает. 

Во-вторых, его не будут переиспользовать где не надо: в случае с circle, некий разработчик Виталий может воспользоваться им в другом месте проекта (в списке например, для точек напротив элемента), а ты решишь, что статус онлайн логичнее например зеленым цветом отображать и поменяешь его здесь. В итоге, даже ни о чем не подозревая, ты задела совсем не связанный с чатом кусок в проекте 😮

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/index.html
> +    <div class="circle"></div>
Примеры несемантичных названий классов:
- .circle
- .line
- .words
- .chel
- .active-input
- .input-special
- .br

Примеры семантичных названий:
- .message, .warning
- .header (в большом проекте не идеально, поскольку слишком широкое понятие, но у тебя вполне подходит)
- .tab
- .time (тоже самое - в большом проекте не очень подходит, лучше более специфичное вроде booking-time, message-time, etc., но у тебя вполне можно)

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/index.html
> +      <hr class="line-1"/>
Уже обсуждали стилизацию за счёт HTML, поэтому здесь просто уточню, что к hr это тоже относится. 
Для создания таких линий по сторонам от "today" попробуй воспользоваться before и after элемент.

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/index.html
> +    <div class="circle"></div>
Вполне нормально, когда названия не идеальные - правильно называть классы, сущности и т.д. это целое искусство. Просто старайся придумывать такие имена, которые:

- Объясняют, за что эта сущность отвечать - например `.message` вполне неплохо дает понять, что это такое и что оно примерно делает.

- Понятны для других разработчиков - в данном случае `.input-special` как раз анти-пример, потому что для тебя он что-то значит, но я совсем не понимаю, что это 🤷‍♂ Вполне подошёл бы обычный `.chat-input`.

- Когда требуется, имеют привязку к контексту - например класс `.time`, который в контексте маленького проекта понятен, но по мере роста быстро потеряет всю семантику (т.е. когда у тебя есть только чат, то в принципе понятно к чему может относиться time, но когда у тебя целая страница с разным функционалом, то попробуй отгадать 🦆). time с контекстом это что-то вроде `.message-time`, `.departure-time` и так далее, т.е. в классе есть уточнение куда он относится.

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/index.html
> +    </div>
time и div представляют из себя единую сущность - сообщение, поэтому их можно было бы сгруппировать в один общий article. 
Это делает разметку чуть более читабельной и помогает потом выделять отдельные части верстки в компоненты.

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/styles.css
> +.html, .body {
Для html не требуется класс, как собственно и для body в этом случае.
Сбросы (resets) и нормализацию (normalization, т.е. приведение стилей к усредненному состоянию между всеми браузерами) можно делать по тегам напрямую.

Эти стили являются больше подготовительными, чтобы ты могла начать работать в комфортных условиях. 

И называть классы `.html` и `.body` нет необходимости - для html классы крайне супер редко задают, а для body используют классы отражающее что представляет из себя веб-страница сама по себе, т.е. `.app`, `.page`, `.my-blog` (имеется в виду, что выбирается название ресурса для класса к body) т. д.

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/styles.css
> +}
А вот background-color действительно вполне нормально в рамках класса определить (только я бы рекомендовал переименовать `.body` во что-нибудь более осмысленное), потому что это не сброс или нормализация (которые делаются обычно еще до основных стилей и применяются напрямую к тегам), а часть дизайна твоего проекта.

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/styles.css
> +  outline: none;
Если отключаешь outline, то добавляй свой кастомный :focus - многие люди привыкли использовать клавиатуру для навигации по интерфейсам. Фокус на свой вкус 👅

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/index.html
> +      <p class="words">You were blocked by the user.</p>
Почему ты решила добавить .words к телу сообщения, с указанными margin, вместо обычных padding-ов на самом message? 

Внутренние отступы для текста можно (и чаще всего стоит) делать через padding. Делать через margin внутренние отступы не стоит, пока для этого нет причины. Поэтому старайся использовать margin для внешнего позиционирования, а padding для внутреннего.

Но всегда найдется исключение конечно, поэтому не забывай смотреть по ситуации. В данном случае можно использовать padding-и для отступов, поэтому причин использовать margin я не вижу. Объяснишь?

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/styles.css
> +  padding-bottom: 10px;
У тебя margin от этого класса вываливается из родителя, поэтому ты используешь padding-bottom, чтобы это компенсировать.

Сможешь объяснить, почему такое происходит с margin?

![image](https://user-images.githubusercontent.com/17354709/62004821-c306e180-b132-11e9-8e4c-712da3656d5c.png)

![image](https://user-images.githubusercontent.com/17354709/62004818-b2566b80-b132-11e9-85d6-e7d43437ef30.png)

2019-07-28 09:28 UTC, VitalyKrenel commented on task-4/styles.css
> +  margin-left: 325px;
Фиксированные отступы - это не очень хорошо, потому что если изменится размер чата (width), то придется исправлять всё, чтобы завязано на старый размер и править.

Сможешь сделать так, чтобы tab был также с левой стороны, но без указания фиксированного отступа❓

2019-07-31 13:14 UTC, Lyashka commented on task-4/index.html
> +      <hr class="line-1"/>
Хорошо. Я думала про использование after и before, но заколебалась при их использовании из-за ввода ограничения на одинаковый вес.

2019-07-31 13:19 UTC, Lyashka commented on task-4/styles.css
> +.html, .body {
Про теги ты имеешь в виду напрямую писать
```
body {
...
}

```
Опять же из-за ограничения на вес я ввела классы, окей, значит класс <html> вообще не используем, можем даже не писать его в css, для body подбираем класс с говорящим названием.

2019-07-31 13:20 UTC, Lyashka commented on task-4/styles.css
> +  outline: none;
Окей, почитаю про :focus

2019-07-31 13:22 UTC, Lyashka commented on task-4/index.html
> +      <p class="words">You were blocked by the user.</p>
Объяснение просто и глупое, не задумывалась о разнице margin и padding, думала нет особой разницы

2019-07-31 13:25 UTC, Lyashka commented on task-4/styles.css
> +  padding-bottom: 10px;
Насколько я помню, то это особенности поведения margin во flex контейнерах.

2019-07-31 13:33 UTC, Lyashka commented on task-4/styles.css
> +  margin-left: 325px;
Это относительное позиционирование или через % имеешь в виду?

2019-07-31 13:35 UTC, Lyashka commented on task-4/index.html
> +    <div class="circle"></div>
- [ ] Изменение семантики классов

2019-07-31 13:36 UTC, Lyashka commented on task-4/index.html
> +      <hr class="line-1"/>
- [ ] Удалить hr элемент, создать через before или after

2019-07-31 13:37 UTC, Lyashka commented on task-4/index.html
> +    </div>
- [ ] объединить сообщение со временем в единую сущность

2019-07-31 13:37 UTC, Lyashka commented on task-4/styles.css
> +}
- [ ] переименовать класс для <body>

2019-07-31 13:38 UTC, Lyashka commented on task-4/styles.css
> +  outline: none;
- [ ] добавить псевдокласс focus

2019-07-31 13:39 UTC, Lyashka commented on task-4/index.html
> +      <p class="words">You were blocked by the user.</p>
- [ ] margin - внешние отступы, padding внутренние, разделить обязанности между ними

2019-07-31 13:40 UTC, Lyashka commented on task-4/styles.css
> +  margin-left: 325px;
- [ ] Убрать фиксированный отступ для времени

2019-07-31 14:31 UTC, VitalyKrenel commented on task-4/index.html
> +      <hr class="line-1"/>
> но заколебалась при их использовании из-за ввода ограничения на одинаковый вес.
К сожалению, нет способа объяснить тебе, когда и как поступать - единственное решение это наработка опыта, с которым приходит понимание, когда какой подход применить, когда можно нарушить правило и так далее.
В большинстве случаев использовать псевдо-классы и -элементы можно - они отличаются от прочих селекторов, потому что ни с чем не конфликтуют.

Т.е. когда я пишу
```css
.my-class::before {

}
```

Я делаю данный селектор более специфичным, но это не важно - ведь к before по нашим правилам можно обратиться только по схеме `.<class-name>::before`, что гарантирует в его случае одинаковую специфичность селекторов. Поэтому правило в данном случае никак не нарушается.

К тому же, твоя задача не столько сделать все селекторы одинакового веса - думаю всего я слишком сложно сформулировал. 

Проще: стилизуй элементы только по классовым селекторам. Нельзя использовать селекторы по тегам (кроме нормализации, ресетов и т.д.) и нельзя использовать селекторы по id (кроме совсем крайних случаев, которые в твоей frontloop практике не предвидятся). Добавлять псевдо-классы и -элементы можно, просто делай это осознано, т.е. будь способна объяснить себе, почему ты так решила поступить. Всё просто 👍 😄

2019-07-31 14:37 UTC, VitalyKrenel commented on task-4/styles.css
> +.html, .body {
Для `html { ... }` иногда тоже требуется прописать что-нибудь вроде padding: 0 или margin: 0, это не запрещается если нужно. Класс добавлять можно, но бесмыслено. Достаточно прямо по тегу.

2019-07-31 14:37 UTC, VitalyKrenel commented on task-4/styles.css
> +.html, .body {
> Про теги ты имеешь в виду напрямую писать
Да

2019-07-31 14:38 UTC, VitalyKrenel commented on task-4/styles.css
> +}
Для? 😅

2019-07-31 14:39 UTC, VitalyKrenel commented on task-4/index.html
> +      <p class="words">You were blocked by the user.</p>
👍

2019-07-31 14:40 UTC, VitalyKrenel commented on task-4/styles.css
> +  padding-bottom: 10px;
Отвечу с объяснением в сообщении.

2019-07-31 14:41 UTC, VitalyKrenel commented on task-4/styles.css
> +  margin-left: 325px;
> через % имеешь в виду?

Через % это тоже за счет привязки к размеру: блок может стать больше, и 70% отступ на 100 пикселях будет как раз, а вот на 1000 слишком много свободного пространства слева 🤷‍♂

2019-08-01 02:52 UTC, Lyashka commented on task-4/styles.css
> +}
![image](https://user-images.githubusercontent.com/48246024/62262220-8c75e300-b420-11e9-81a5-cef3d654e8ff.png)

Забавно)

2019-08-01 07:02 UTC, Lyashka commented on task-4/index.html
> +      <hr class="line-1"/>
Во втором случае (то, что было ранее .line-2) сделала через boder, так как нижняя часть (.chat-input) имеет `flex-direction: row;`, а верхняя (.message) сделана инлайн-блоком, в итоге при добавлении, линия вообще не отображается (схлопывание?).

2019-08-01 07:45 UTC, Lyashka commented on task-4/styles.css
> +.html, .body {
- [ ] убрать класс html, добавить корректные классы body

2019-08-01 09:13 UTC, Lyashka commented on task-4/index.html
> +      <p class="words">You were blocked by the user.</p>
Оставила padding у <p>, чтобы происходило центрирование, если фраза короткая (одна строка)
![image](https://user-images.githubusercontent.com/48246024/62281062-c44b4d80-b455-11e9-8ff1-c9a7243c8dc8.png)

2019-08-01 09:17 UTC, Lyashka commented on task-4/styles.css
> +  outline: none;
Надеюсь я верно поняла задание

2019-08-01 11:46 UTC, Lyashka commented on task-4/styles.css
> +  margin-left: 325px;
Осуществила через flex, обнулила ненужные margin

2020-08-31 04:07 UTC, merged