Пятое выполненное задание FrontLoops
Lyashka/FrontLoops-tasks pull request #6
Opened 2019-07-25 04:50 UTC by Lyashka

2019-07-29 19:25 UTC, VitalyKrenel requested changes

2019-07-29 19:25 UTC, VitalyKrenel commented on task-5/index.html
> +      </div>
Попробуй применить мысли из предыдущего PR касательно именования классов https://github.com/Lyashka/FrontLoops-tasks/pull/5#discussion_r307991517

2019-07-29 19:25 UTC, VitalyKrenel commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
Сложные свойства иногда стоит расписать на отдельные. Например здесь случай с `background-position / background-size`, который многие разработчики могут сходу не вспомнить (в том числе и ты, если долго не будешь сталкиваться с этим синтаксисом), поэтому вполне нормально разделить этот background на 3 свойства:

```CSS
background: url(img/background.jpg) no-repeat;
background-position: center;
background-size: 100%;
```

В каждом отдельном случае нужно руководствоваться здравым смыслом и своими ощущениями. Мне вот это видится некоторой "крипотой", поэтому его я отношу к случаю, когда можно расписать в несколько свойств и это действительно увеличит читабельность и поддерживаемость. 🚀

2019-07-29 19:25 UTC, VitalyKrenel commented on task-5/styles.css
> +.html, .body {
В предыдущем уже писал, на всякий случай продублирую https://github.com/Lyashka/FrontLoops-tasks/pull/5#discussion_r307992601

2019-07-29 19:25 UTC, VitalyKrenel commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
Кстати, нам точно нужен background-size в этом случае?

2019-07-29 19:31 UTC, VitalyKrenel commented
На viewport меньшем чем ~1500px width, задний фон не занимает всё доступное пространство у страницы. 
![image](https://user-images.githubusercontent.com/17354709/62076212-c348cf00-b24f-11e9-8511-6372115c42cd.png)

Сделай, пожалуйста так, чтобы он занимал всё пространство, независимо от размера [viewport](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#viewport)'а.

![image](https://user-images.githubusercontent.com/17354709/62076457-626dc680-b250-11e9-9a09-bb7af6fbc255.png)

2019-07-29 19:50 UTC, VitalyKrenel requested changes

2019-07-29 19:50 UTC, VitalyKrenel commented on task-5/styles.css
> +  padding-bottom: 55px;
В прошлом PR я спрашивал про не совсем уместное использование margin для внутренних отступов https://github.com/Lyashka/FrontLoops-tasks/pull/5#discussion_r307993007. Здесь ситуация точно такая же, но совершенно другая (:trollface:):

`.country-completely` отделяет полные имена стран от всего кодов аэропортов сверху и прочим данным полета снизу. 
То есть сам блок занимает совсем немного места, ниже него идёт разрыв, или как обычно говорим, отступ.

Если использовать, как сделал ты, внутренний отступ (padding), то это значит, что область снизу относится к данной блоку со странами. Однако это обычное свободное пространство, оно ведь никак к дизайну блока со странами не причастно. 

Сейчас при добавлении, например, `background-color` стилизуется также и отступ, потому что он определен как **внутренний** для блока `.country-completely `, вместо внешнего (margin).

![image](https://user-images.githubusercontent.com/17354709/62077133-0c018780-b252-11e9-9052-cc532b1039ed.png)

Используй padding для внутренних отступов, которые относятся к элементам напрямую. Для остального позиционирования (внешнего, когда элементы как бы двигают друг друга, создавая нужный лейаут) используй margin.

Стандартное напоминание, что всегда могут быть исключения и для определенных дизайнерских решений или способов позиционирования может потребовать использовать padding вместо margin (or vice versa).

2019-07-29 19:54 UTC, VitalyKrenel commented on task-5/styles.css
> +  padding-bottom: 55px;
`.country-completely` - один из примеров озвученной проблемы в задании, для большинства остальных тоже нет необходимости использовать внутренние отступы вместо внешних.

Однако в случае класса `.all` использование padding-ов оправданно - они отвечают за внутренний отступ для карточки онлайн-билета, чтобы добавить свободного пространства между содержимым карточки и её границами.

2019-07-31 13:42 UTC, Lyashka commented on task-5/index.html
> +      </div>
Да, я поняла, во всех заданиях нужно менять будет :D

2019-07-31 13:44 UTC, Lyashka commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
Я думала, что наоборот удобнее, чтобы свойства были "в куче" так сказать. Окей, буду знать.

2019-07-31 13:45 UTC, Lyashka commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
- [ ] повысить читабельность background, чекнуть свойство background-size.

2019-07-31 13:45 UTC, Lyashka commented on task-5/index.html
> +      </div>
- [ ] Изменить семантику классов

2019-07-31 13:47 UTC, Lyashka commented on task-5/styles.css
> +.html, .body {
- [ ] Название body изменить, .html убрать

2019-07-31 13:49 UTC, Lyashka commented on task-5/styles.css
> +  padding-bottom: 55px;
- [ ] margin - внешние отступы, padding внутренние, разделить обязанности между ними

2019-07-31 14:46 UTC, VitalyKrenel commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
> Я думала, что наоборот удобнее, чтобы свойства были "в куче" так сказать. Окей, буду знать.

Писать проще и быстрее, но читать дольше и сложнее редактировать. Так как большинство разработчиков 70% (цифра с потолка, но близкая) проводят именно **читая** код, то важнее следовать практикам, которые увеличивают читабельность, чем тем, что быстрее писать 👓

2019-07-31 14:47 UTC, VitalyKrenel commented on task-5/styles.css
> +  padding-bottom: 55px;
👍

2019-08-01 17:47 UTC, Lyashka commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
Свойство background-size нужно, так как картинка с достаточно большим разрешением, поэтому задаём background-size: 100%, картинка занимает всё окно браузера.

2019-08-01 18:09 UTC, Lyashka commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
Насчёт viewport, картинка-фон очень широкая, поэтому я поставила 100%, высота остаётся в значении auto и подстраивается под ширину, других вариантов я не вижу, хотя и понимаю, что он не идеален (баловалась с различными значениями, получалось только хуже).

2019-08-01 18:09 UTC, Lyashka commented on task-5/styles.css
> +  background: no-repeat center/100% url(img/background.jpg);
- [ ] Изменить картинку viewport

2019-08-01 18:46 UTC, Lyashka commented on task-5/index.html
> +      </div>
Для многих классов очень сложно подобрать названия, в них нет логической нагрузки (как ты пример приводил про кружок), поэтому назвала многие по-тупому

2020-08-31 04:07 UTC, merged